name: Galio
description: Build better apps using React Native
website_url: https://galio.io/
github_url: https://github.com/galio-org/galio
keywords: react native, native, ios, android, mobile app, mobile apps, mobile framework, app design, galio, galio framework, framework
twitter_handle: galio
facebook_handle: galio
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
